### ISSUE TITLE
Supporting Embedded and Nullable features from gogo proto

### ISSUE THREAD

**Issue by sudhiaithal** [planetscale/vtprotobuf#108]
We wanted to migrate away from gogo protobuf but we are are using gogo's embedded and nullable features.  I see that VTProtobuf does not support that yet.

I have 2 questions 

1. Is there a plan to add this any time soon?
2. Will the community be willing to accept the change if we propose it?

**Comment by vmg** [comment]
Hey @sudhiaithal! One of the core design choices of vtprotobuf is that it's implemented as a plug-in on top of the official ProtoBuf Go implementation. This makes maintaining it much more straightforward, but it comes with some limitations. As a plug-in, we can generate e.g. extension methods to speed up (de)serialization, but we cannot perform changes to the actual shapes of the generated structs, because those are controlled by the upstream generator, not by us. The two specific features you suggest would require changing the shapes of the structs, so you would have to rewrite vtprotobuf from scratch to support those. It'd be a different project altogether! 

So sadly those two are out of scope. Unless you can think of a magical way to support them without changing struct shapes (that'd be cool!)

**Comment by sudhiaithal** [comment]
Thanks @vmg for responding. Yes, the problem is we need to generate struct with embedded field. Official go implementation is also not open to change from the FAQs here https://go.dev/blog/protobuf-apiv2
