### ISSUE TITLE
Proto2 Support

### ISSUE THREAD

**Issue by gmather** [planetscale/vtprotobuf#11]
Is it expected that the vtproto files aren't currently being generated for proto2 files or do I have something misconfigured?

**Comment by vmg** [comment]
Nope, this is expected (and I unfortunately forgot to document it :sweat:). I intentionally skipped support for proto2 because Vitess doesn't use it and it makes memory pooling trickier. I take it your project is stuck in proto2 and not planning to upgrade to proto3? I'm still unsure of whether the additional complexity of supporting legacy proto2 is worth it, given the minimal use case.

**Comment by gmather** [comment]
The specific case is some legacy proto2 messages getting referenced in proto3 messages which causes compile errors as the vtproto helpers are not generated but are expected to exist in the proto3 helpers.

**Comment by euroelessar** [comment]
As an additional entry point - our codebase does still have hundreds of proto2 files and the migration would be tricky and often risky.

This makes me interested if you're willing to accept patches to support generation (un)marshal/size methods for proto2?

I understand that pooling logic is tricky and we could skip it & ask people to migrate to proto3 for this additional feature.

**Comment by vmg** [comment]
@euroelessar: sure thing. It actually shouldn't be a massive change, some of the generators already have a `proto3` param that toggles between proto2 and proto3 generated code. It's just a matter of finishing up all the corner cases. If you send a PR I'll review it.
