### ISSUE TITLE
ext.proto file is missing

### ISSUE THREAD

**Issue by codesoap** [planetscale/vtprotobuf#142]
In the README it is described that one can use `import "github.com/planetscale/vtprotobuf/vtproto/ext.proto";` in `.proto` files so that `vtproto.mempool` can be used. This does not work for me; when trying to generate code, I get this error:
```
Import "github.com/planetscale/vtprotobuf/vtproto/ext.proto" was not found or had errors.
```

I can see that the file was removed in acbcee4a33a285d8a5de689d6b6fcbf1b7fb2f60. Was this a mistake?

**Comment by vmg** [comment]
Hey, you're looking at the wrong path. The file is properly namespaced in the repository: https://github.com/planetscale/vtprotobuf/blob/main/include/github.com/planetscale/vtprotobuf/vtproto/ext.proto

In order to access it, you need to add the root of the `include` folder to the includes of your `protoc` invocation, with the `-I` flag. There are many ways to do this; you can use `go mod` to find the path of your `vtprotobuf module`:

```
protoc -I${go list -m -f '{{.Dir}}/include' github.com/planetscale/vtprotobuf} ...
```

You can also manually vendor the `ext.proto` file to your repository to not depend on the module, etc.

**Comment by codesoap** [comment]
I see, I misunderstood the README. I thought the URL was a constant and didn't realize one should include the `ext.proto` file in the project repo. Thanks for the explanation!
