### ISSUE TITLE
Add support for non nullable objects - similar to gogoproto.nullable 

### ISSUE THREAD

**Issue by pavolloffay** [planetscale/vtprotobuf#4]
Thanks for putting this library together! 

Would it be possible to add support for non nullable objects - similar to gogo annotation `gogoproto.nullable`?

**Comment by vmg** [comment]
This is explained in the announcement blog post. Let me quote it directly (emphasis mine):

> The vtprotobuf compiler makes a different design choice compared to Gogo ProtoBuf: it is not a fork of the APIv2 compiler, but an independent plug-in that runs alongside the upstream compiler for APIv2 and generates the optimized code as opt-in helpers. **This is a trade-off because it means that we cannot implement some of the optimizations that Gogo supports, like making message fields non-nullable**, or aliasing the generated types in the generated ProtoBuf messages. These are Gogo ProtoBuf features that some Go projects have used successfuly to reduce the amount of garbage generated when handling Protocol Buffer messages, but Vitess has never opted-in into those, so it didn’t make sense for us to port them to our APIv2 generator.

Implementing this would require a full fork of the ProtoBuf compiler, and the generated messages wouldn't be fully compatible with the runtime either. I'm afraid to say that despite this being a powerful optimization, we're going to punt on it for now, because the maintenance burden it implies is just too large. Sorry!
