### ISSUE TITLE
Using stack trace feature for returned errors

### ISSUE THREAD

**Issue by ertaquo** [planetscale/vtprotobuf#58]
Hello.
There's stack trace feature in official package [`github.com/pkg/errors`](https://pkg.go.dev/github.com/pkg/errors#section-readme).
I'd offer to wrap returned errors in generated files with `errors.WithStack(err)` from this package.
Other words, let's turn this generated code:
```go
if err != nil {
	return err
}
if (skippy < 0) || (iNdEx+skippy) < 0 {
	return ErrInvalidLength
}
if (iNdEx + skippy) > l {
	return io.ErrUnexpectedEOF
}
```
into that:
```go
if err != nil {
	return errors.WithStack(err)
}
if (skippy < 0) || (iNdEx+skippy) < 0 {
	return errors.WithStack(ErrInvalidLength)
}
if (iNdEx + skippy) > l {
	return errors.WithStack(io.ErrUnexpectedEOF)
}
```
That would be extremely useful for debug purposes.
I could prepare pull request if you wish.

**Comment by vmg** [comment]
Hey @ertaquo! The package you suggest, `[github.com/pkg/errors](https://pkg.go.dev/github.com/pkg/errors#section-readme)`, is actually not official at all (even if the `pkg` namespace may lead you to believe otherwise) and is not endorsed by the Go core team. As such, I don't think it's a reasonable thing to force a dependency on this third party package.

If you really need stack traces, there are many options to inject them into your generated files without modifying `vtprotobuf`. For instance, you can run a rewrite step in your build pipeline that injects `pkg/errors` or whichever error wrapper package you want to use in the future.

Cheers!
