### ISSUE TITLE
unknown feature: "clone"

### ISSUE THREAD

**Issue by delaneyj** [planetscale/vtprotobuf#74]
Works fine...
```bash
--go-vtproto_opt=features=marshal+unmarshal+size+pool \
```

Making sure to get latest `go install github.com/planetscale/vtprotobuf/cmd/protoc-gen-go-vtproto@latest`
```bash
--go-vtproto_opt=features=marshal+unmarshal+size+pool+clone \
```
Gives `--go-vtproto_out: unknown feature: "clone"`

**Comment by delaneyj** [comment]
`go install github.com/planetscale/vtprotobuf/cmd/protoc-gen-go-vtproto@0ae748fd2007a8ade11db4174599f4ba967b3f37
` "fixes" it but I'm sure that's not the intention.

**Comment by nockty** [comment]
This sounds like it happened because the feature was not released at that time. It was part of version [v0.4.0](https://github.com/planetscale/vtprotobuf/releases/tag/v0.4.0) which was released on January 27th.

`clone` should now work when installing with `@latest`, I've been using it successfully on my side. So, I'll just close this issue but feel free to let me know if you are still hitting something unexpected here.
