### ISSUE TITLE
ReturnToVTPool() recursive?

### ISSUE THREAD

**Issue by jacobmarble** [planetscale/vtprotobuf#8]
When `func (p *YourProto) ReturnToVTPool()` is called, children of `YourProto` that implement method `ReturnToVTPool()` should also be returned to the pool.

**Comment by jacobmarble** [comment]
I notice that, for non-repeated message fields, `ReturnToVTPool()` is called by the parent's `ResetVT()` method. Repeated fields do not receive this treatment, however.

**Comment by jacobmarble** [comment]
It seems the idea is that a nested message structure should be pooled only at the top level parent. Repeated fields are cleared by `ResetVT()`, but their contents (pointers to other messages) are not pooled, even if the repeated child message definition is marked as such.

**Comment by vmg** [comment]
Hey @jacobmarble! What you're seeing is an optimization for repeated fields with pooled messages: when clearing a repeated field, instead of returning every single message to the pool, what we do is **leaving them in the non-addressable part of the slice** (i.e. into its capacity). This way, when unmarshaling again into the same message, instead of `append`-ing to a zero-length slice, we can check if the current unaddressed capacity for the message contains messages, and if so, use those by simply growing the addressable length of the slice.

For every single benchmark I've been able to synthesize, this is _always_ significantly faster than returning every single object to the pool (and then fetching from the pool when unmarshaling). Does this behavior surprise you, or is it breaking some of your expectations...?

**Comment by jacobmarble** [comment]
@vmg thanks for explaining, I think I understand. The behavior does surprise me, but I'm not sure it's wrong.
